# Generated by Django 4.0.4 on 2022-05-31 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codesimple', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='comment',
            name='blogPost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='codesimple.blogpost'),
        ),
    ]
