# Generated by Django 4.0.4 on 2022-05-31 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codesimple', '0005_remove_comment_created_by_alter_comment_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blogPost',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='codesimple.blogpost'),
            preserve_default=False,
        ),
    ]
