# Generated by Django 4.0.4 on 2022-05-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesimple', '0008_comment_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(default=29, max_length=50),
            preserve_default=False,
        ),
    ]
